language: node_js

node_js:
  - stable

notifications:
  email:
    recipients:
      - moutou.antoine@hotmail.fr
    on_success: never
    on_failure: always

# This is needed to avoid building all the tags pushed by travis
branches:
  except:
    - /^v?\d+\.\d+\.\d+$/

before_install:
  # Create a git tag of the new version to use
  # If package.json major and minor versions match last tag, then increment last tag. Else use package.json major.minor.0.
  - "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1\"0\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
  # Update package.json based on the git tag we just created
  - npm --no-git-tag-version version from-git

stages:
  - install
  - test
  - name: version
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: install
      script: npm install
    - stage : test
      script : npm test
    - stage: version
      deploy:
        provider: script
        skip_cleanup: true
        script: git push --tags
    - stage: deploy
      deploy :
        provider: npm
        email: "moutou.antoine@hotmail.fr"
        api_key: "dc34d845-41d9-48c1-8973-a6286158af61"
