language: node_js

node_js:
  - stable

notifications:
  email:
    recipients:
      - moutou.antoine@hotmail.fr
    on_success: never
    on_failure: always

stages:
  - install
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: install
      script: npm install
    - stage : test
      script : npm test
    - stage: deploy
      script : npm version patch
      deploy :
        provider: npm
        email: "moutou.antoine@hotmail.fr"
        api_key: "dc34d845-41d9-48c1-8973-a6286158af61"
